# Generated by Django 3.0.3 on 2020-05-04 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200504_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Post_image',
            field=models.ImageField(default='blog/static/usama.jpg', upload_to='blog/imagesupload'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 20, 13, 5, 124033, tzinfo=utc)),
        ),
    ]
