# Generated by Django 3.0.3 on 2020-05-06 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200506_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Post_image_height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Post_image_width',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 1, 9, 11, 301081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 6, 1, 9, 11, 301081, tzinfo=utc)),
        ),
    ]
