# Generated by Django 3.0.3 on 2020-05-04 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200504_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 20, 53, 34, 384640, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Post_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
